<?php $advanced  = array(
	"(a)",
	"[a]",
	"\\lbrace{a}\\rbrace",
	"\\frac{a+b}{c+d}",
	"\\vec{a}",
	"\\binom {a} {b}",
	"{a \brack b}",
	"{a \brace b}",
	"\\sin",
	"\\cos",
	"\\tan",
	"\\cot",
	"\\sec",
	"\\csc",
	"\\sinh",
	"\\cosh",
	"\\tanh",
	"\\coth",
	"\\bigcap {a}",
	"\\bigcap_{b}^{} a",
	"\\bigcup {a}",
	"\\bigcup_{b}^{} a",
	"\\coprod {a}",
	"\\coprod_{b}^{} a",
	"\\prod {a}",
	"\\prod_{b}^{} a",
	"\\sum_{a=1}^b",
	"\\sum_{b}^{} a",
	"\\sum {a}",
	"\\underset{a \\to b}\\lim",
	"\\int {a}",
	"\\int_{b}^{} a",
	"\\iint {a}",
	"\\iint_{b}^{} a",
	"\\int_{a}^{b}{c}",
	"\\iint_{a}^{b}{c}",
	"\\iiint_{a}^{b}{c}",
	"\\oint{a}",
	"\\oint_{b}^{} a"
); ?>